version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres

  web:
    build: . 
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: django

  nginx:
    build: ./nginx
    ports:
            - 80:80
    depends_on:
            - web
    container_name: nginx

volumes:
  postgres_data: