version: 2.1

orbs:
  python: circleci/python@1.5.0


jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - setup
  test:
    docker:
      - image: circleci/python:3.6.4
      - image: circleci/postgres:11.6        
        name: "db"
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: ""

    steps:
      - setup
      - run:
          name: migrate
          command: python manage.py migrate
      - run:
          name: run test
          command: python manage.py pytest .


workflows:
  sample:
    jobs:
      - build
      - test:
          requires:
            - build
