version: 2

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:2022.10.1
    steps:
    # Djangoのテストを実行
      - checkout
      - run:
          name: make env file
          command: |
            echo SECRET_KEY=${SECRET_KEY} >> .env
            echo ${SECRET_KEY}
            echo POSTGRES_USER=${POSTGRES_USER} >> .env
            echo POSTGRES_DB=${POSTGRES_DB} >> .env
            echo POSTGRES_PASSWORD=${POSTGRES_PASSWORD} >> .env
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: docker ps
          command: docker ps
      # - run:
      #     name: collectstatic
      #     command: docker-compose run web python ./manage.py collectstatic
      - run:
          name: migrate
          command: docker-compose run web python ./manage.py migrate
      - run:
          name: test
          command: docker-compose run web pytest .
      - run:
          name: docker-compose down
          command: docker-compose down


workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test