# Generated by Django 4.1.1 on 2022-12-27 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, verbose_name='ラベル')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=50, verbose_name='タスク')),
                ('date_start', models.DateTimeField(null=True)),
                ('date_limit', models.DateTimeField(null=True)),
                ('comment', models.TextField(blank=True, max_length=255, null=True, verbose_name='コメント内容')),
                ('status', models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'INACTIVE')], default=0)),
                ('deleted', models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'INACTIVE')], default=0)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='Todolist.priority')),
            ],
        ),
    ]
